services:
  db:
    image: postgres:15
    container_name: postgres_alt_new
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todolist
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: todo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    ports:
      - "8080:8080"

volumes:
  db-data:
